#!/bin/bash

MY_SCRIPT=`basename "$0"`

COMPANY=cb

MAVEN_HOME="$HOME/.m2"
MAVEN_CONF_DIR="$MAVEN_HOME"

if [ -f $MAVEN_CONF_DIR/COMPANY ] && [ -f $MAVEN_CONF_DIR/settings.default.xml ]
then 
  rm -f $MAVEN_CONF_DIR/COMPANY
  cp $MAVEN_CONF_DIR/settings.default.xml $MAVEN_CONF_DIR/settings.xml
  touch $MAVEN_CONF_DIR/DEFAULT
elif [ -f $MAVEN_CONF_DIR/DEFAULT ] && [ -f $MAVEN_CONF_DIR/settings.$COMPANY.xml ]
then
  rm -f $MAVEN_CONF_DIR/DEFAULT
  cp $MAVEN_CONF_DIR/settings.$COMPANY.xml $MAVEN_CONF_DIR/settings.xml
  touch $MAVEN_CONF_DIR/COMPANY
else 
  if [ ! -f $MAVEN_CONF_DIR/settings.default.xml ]
  then 
    echo "The $MAVEN_CONF_DIR/settings.default.xml does not exists."
  fi
  if [ ! -f $MAVEN_CONF_DIR/settings.$COMPANY.xml ]
  then 
    echo "The $MAVEN_CONF_DIR/settings.$COMPANY.xml does not exists."
  fi
fi

cat $MAVEN_CONF_DIR/settings.xml
