#!/bin/bash

rm -rf .project .classpath .settings .idea;

for a in *; do { 
  if [ -d $a ]; 
  then 
    echo $a;
    rm -rf $a/.project;
    rm -rf $a/.classpath;
    rm -rf $a/.settings;
    rm -rf $a/.idea;
  fi
}; done;