#!/bin/bash

clean_ide_files() {
    a=$1;
    echo $a;
    rm -rf $a/.project;
    rm -rf $a/.classpath;
    rm -rf $a/.settings;
    rm -rf $a/.idea;
    rm -rf $a/.factoryPath;
    rm -rf $a/*.iml;
}

clean_ide_files .

for a in *; do { 
  if [ -d $a ]; 
  then 
    clean_ide_files $a;
  fi
}; done;