#!/bin/bash

COMMENT='a very simple commit';
BRANCH='master';

###
# CMD
###
press_to_continue() {
  echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=";
  echo "press <<ENTER>> to continue";
  echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=";
  read;
}

###
# SHOW
###
show_step() {
  NAME=$1;
  POS=$2;
  FINAL=10
  echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=";
  echo "Step: "$NAME" ("$POS"/"$FINAL")";
  echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=";
}

###
# PROTOTYPE
###
prototype() {
  COMMAND=$1;
  POS=$2;

  case "$COMMAND" in
    status )
      show_step "GIT STATUS" "$POS";
      git status;
      ;;
    pull )
      show_step "GIT PULL" "$POS";
      git pull origin $BRANCH;
      ;;
    add )
      show_step "GIT ADD" "$POS";
      git add .;
      ;;
    commit )
      show_step "GIT COMMIT" "$POS";
      git commit -m "$COMMENT";
      ;;
    push )
      show_step "GIT PUSH" "$POS";
      git push origin $BRANCH;
      ;;
  esac

  #press_to_continue;
}

###
# MAIN
###
if [ $# == 2 ]
then
  BRANCH=$1;
  COMMENT=$2;
else 
  if [ $# == 1 ]
  then
    BRANCH=$1;
  fi
fi

prototype "status" "1"
prototype "pull" "2"
prototype "status" "3"
prototype "add" "4"
prototype "status" "5"
prototype "commit" "6"
prototype "status" "7"
prototype "pull" "8"
prototype "status" "9"
prototype "push" "10"
