#!/bin/bash 

rm -rf $HOME/jboss-6.1.0.Final/server/default/data
rm -rf $HOME/jboss-6.1.0.Final/server/default/tmp
rm -rf $HOME/jboss-6.1.0.Final/server/default/work

cd $HOME/jboss-6.1.0.Final/bin

./run.sh
