#!/bin/bash

if [ "$#" -eq "1" ] 
then
    ps aux | grep $1 | grep -v "/home/anderson/sisbride/bin/killallprocess" | grep -v "grep" | awk -F' ' '{ print $2 }' 
else 
    echo "usage: killallprocess PATTERN"
fi

exit $?
