#!/bin/bash

JBOSS_4_HOME=/home/anderson/sisbride/apps/jboss-4.2.3.GA;
JBOSS_5_HOME=/home/anderson/sisbride/apps/jboss-5.1.0.GA;
JBOSS_6_HOME=/home/anderson/sisbride/apps/jboss-eap-6.1;

rm -rf $JBOSS_4_HOME/server/default/data;
rm -rf $JBOSS_4_HOME/server/default/log;
rm -rf $JBOSS_4_HOME/server/default/tmp;
rm -rf $JBOSS_4_HOME/server/default/work;

rm -rf $JBOSS_4_HOME/server/portal/data;
rm -rf $JBOSS_4_HOME/server/portal/log;
rm -rf $JBOSS_4_HOME/server/portal/tmp;
rm -rf $JBOSS_4_HOME/server/portal/work;

rm -rf $JBOSS_4_HOME/server/app/data;
rm -rf $JBOSS_4_HOME/server/app/log;
rm -rf $JBOSS_4_HOME/server/app/tmp;
rm -rf $JBOSS_4_HOME/server/app/work;

rm -rf $JBOSS_5_HOME/server/default/data;
rm -rf $JBOSS_5_HOME/server/default/log;
rm -rf $JBOSS_5_HOME/server/default/tmp;
rm -rf $JBOSS_5_HOME/server/default/work;

rm -rf $JBOSS_5_HOME/server/app/data;
rm -rf $JBOSS_5_HOME/server/app/log;
rm -rf $JBOSS_5_HOME/server/app/tmp;
rm -rf $JBOSS_5_HOME/server/app/work;

rm -rf $JBOSS_6_HOME/standalone/data;
rm -rf $JBOSS_6_HOME/standalone/log;

exit $?
