#!/bin/bash

TIMESTAMP=`date +"%Y%m%d-%H%M%S"`;

##
# proxy config: http://pac.zscaler.net/sicoob.com.br/sicoob.pac
##

##
# backup $file
#
backup_file() {
  cp $1 $1.$TIMESTAMP;
}

##
# append text parameter $1 to file parameter $2
#
append_text_to_file() {
  echo $1 >> $2;
}

##
# setting 
#
configure_environment() {
  FILE=/etc/environment;
  backup_file $FILE;
  append_text_to_file "http_proxy=\"$http_proxy\"" $FILE;
  append_text_to_file "https_proxy=\"$https_proxy\"" $FILE;
  append_text_to_file "ftp_proxy=\"$ftp_proxy\"" $FILE;
  append_text_to_file "no_proxy=\"$no_proxy\"" $FILE;
}

##
# export proxy variables
#
export_proxy_variables() {
  export http_proxy="http://189.8.69.36:80/"
  export https_proxy="http://189.8.69.36:80/"
  export ftp_proxy="http://189.8.69.36:80/"
  export no_proxy="localhost,127.0.0.1,.sicoob.com.br,.bancoob.com.br,.homologacao.com.br,svn.sicoob.com.br"
}

##
# configure gsettings
#
configure_gsettings() {
  gsettings set org.gnome.system.proxy ignore-hosts "['localhost', '127.0.0.0/8', '*sicoob.com.br', '*bancoob.com.br', '*bancoob.br', '*homologacao.com.br', 'jb*', 'gis*', 'sicoob*']"
  
  gsettings set org.gnome.system.proxy.ftp host "189.8.69.36"
  gsettings set org.gnome.system.proxy.ftp port 80
  
  gsettings set org.gnome.system.proxy.http host "189.8.69.36"
  gsettings set org.gnome.system.proxy.http port 80

  gsettings set org.gnome.system.proxy.https host "189.8.69.36"
  gsettings set org.gnome.system.proxy.https port 80
}

##
# main
#
if [ `whoami` != "root" ]; then
  echo "you need to be root to execute this script";
  exit 1;
else
  export_proxy_variables
  configure_environment
  configure_gsettings
  exit 0;
fi


