#!/bin/bash

##
# proxy config: http://pac.zscaler.net/sicoob.com.br/sicoob.pac
##

##
# configure proxy 
#
configure_proxy() {

  ###
  # route default with proxy
  ###
  #default         10.238.34.126   0.0.0.0         UG    0      0        0 eth0
  #10.238.34.0     *               255.255.255.128 U     1      0        0 eth0

  ##
  # environment
  ##
  sudo cp /etc/environment.proxy /etc/environment;

  ##
  # gsettings
  ##
  gsettings set org.gnome.system.proxy ignore-hosts "['localhost', '127.0.0.0/8', '*sicoob.com.br', '*bancoob.com.br', '*bancoob.br', '*homologacao.com.br', 'jb*', 'gis*', 'sicoob*']"
  gsettings set org.gnome.system.proxy.ftp host "189.8.69.36"
  gsettings set org.gnome.system.proxy.ftp port 80
  gsettings set org.gnome.system.proxy.http host "189.8.69.36"
  gsettings set org.gnome.system.proxy.http port 80
  gsettings set org.gnome.system.proxy.https host "189.8.69.36"
  gsettings set org.gnome.system.proxy.https port 80
  gsettings set org.gnome.system.proxy mode "manual"

  ##
  # routes
  ##
  sudo route del -host 208.100.40.44 gw 10.238.34.126 dev eth0
  sudo route del -host 199.168.148.20 gw 10.238.34.126 dev eth0
  sudo route del -host 189.8.69.36 gw 10.238.34.126 dev eth0
  sudo route del -host 192.168.100.128 gw 10.238.34.126 dev eth0
  sudo route del -net 10.0.0.0 netmask 255.0.0.0 gw 10.238.34.126 dev eth0
  sudo route add -net 0.0.0.0 netmask 0.0.0.0 gw 10.238.34.126 dev eth0
  sudo route del -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.1.1 dev wlan0
}

##
# configure no proxy 
#
configure_noproxy() {

  ##
  # route default without proxy
  ##
  #default         192.168.1.1     0.0.0.0         UG    0      0        0 wlan0
  #10.0.0.0        10.238.34.126   255.0.0.0       UG    0      0        0 eth0
  #10.238.34.0     *               255.255.255.128 U     1      0        0 eth0
  #189.8.69.36     10.238.34.126   255.255.255.255 UGH   0      0        0 eth0
  #192.168.1.0     *               255.255.255.0   U     9      0        0 wlan0
  #correio.sicoob. 10.238.34.126   255.255.255.255 UGH   0      0        0 eth0
  #199.168.148.20  10.238.34.126   255.255.255.255 UGH   0      0        0 eth0
  #ip44.208-100-40 10.238.34.126   255.255.255.255 UGH   0      0        0 eth0

  ##
  # environment
  ##
  sudo cp /etc/environment.noproxy /etc/environment;

  unset http_proxy
  unset https_proxy
  unset ftp_proxy
  unset no_proxy

  ##
  # gsettings
  ##
  gsettings set org.gnome.system.proxy ignore-hosts "[]"
  gsettings set org.gnome.system.proxy.ftp host ""
  gsettings set org.gnome.system.proxy.ftp port 0
  gsettings set org.gnome.system.proxy.http host ""
  gsettings set org.gnome.system.proxy.http port 0
  gsettings set org.gnome.system.proxy.https host ""
  gsettings set org.gnome.system.proxy.https port 0
  gsettings set org.gnome.system.proxy mode "none"
  
  ##
  # routes
  ##
  #etudo ip route flush table all  
  #sudo ip link set wlan0 up  
  sudo route add -host 208.100.40.44 gw 10.238.34.126 dev eth0
  sudo route add -host 199.168.148.20 gw 10.238.34.126 dev eth0
  sudo route add -host 189.8.69.36 gw 10.238.34.126 dev eth0
  sudo route add -host 192.168.100.128 gw 10.238.34.126 dev eth0
  sudo route add -net 10.0.0.0 netmask 255.0.0.0 gw 10.238.34.126 dev eth0
  sudo route del -net 0.0.0.0 netmask 0.0.0.0 gw 10.238.34.126 dev eth0
  sudo route add -net 0.0.0.0 netmask 0.0.0.0 gw 192.168.1.1 dev wlan0
}

##
# show message error
##
show_error() {
  echo "usage: network [proxy|noproxy|show]"
}

##
# show configure
##
show_report() {
  TIME=1;
  
  sudo cat /etc/environment;
  
  sleep $TIME;
  
  gsettings get org.gnome.system.proxy ignore-hosts
  gsettings get org.gnome.system.proxy.ftp host
  gsettings get org.gnome.system.proxy.ftp port
  gsettings get org.gnome.system.proxy.http host
  gsettings get org.gnome.system.proxy.http port
  gsettings get org.gnome.system.proxy.https host
  gsettings get org.gnome.system.proxy.https port
  gsettings get org.gnome.system.proxy mode
  
  sleep $TIME;

  sudo route;
}

##
# main
#
if [ $# -eq 1 ]; then
  REDE=$1;
  if [ $REDE = "proxy" ]; then
    configure_proxy;
  else 
    if [ $REDE = "show" ]; then
      show_report;
    else
      configure_noproxy;
    fi
  fi
else 
  show_error;
  #exit 1;
fi

#exit 0;



