#!/bin/bash

DIR=/home/anderson/sisbride/bin;
MVN_PATH=/home/anderson/sisbride/tools/apache-maven-$2;

case $1 in
  s )
    cp $DIR/settings.xml.sicoob $MVN_PATH/conf/settings.xml;
    cat $MVN_PATH/conf/settings.xml;
    ;;
  d )
    cp $DIR/settings.xml.default $MVN_PATH/conf/settings.xml;
    cat $MVN_PATH/conf/settings.xml;
    ;;
  dp )
    cp $DIR/settings.xml.default.proxy $MVN_PATH/conf/settings.xml;
    cat $MVN_PATH/conf/settings.xml;
    ;;
  * )
    echo "usage: set-maven-config [s|d|dp] MAVEN_VERSION"
    echo "param: s - Maven settings with enterprise repository"
    echo "param: d - Default Maven settings"
    echo "param: dp - Default Maven settings with enterprise proxy"
    ;;
esac