#!/bin/bash

DIR=/home/anderson/sisbride/bin;
SISBRIDE_TOOLS=/home/anderson/sisbride/tools;
MVN_PATH=$SISBRIDE_TOOLS/apache-maven-$2;

copy_file() {
  cp $1 $2;
  cat $2;
}

show_error() {
    echo "usage: set-maven-config [s|d|dp] MAVEN_VERSION"
    echo "param: s or sicoob - Maven settings with enterprise repository"
    echo "param: d or default- Default Maven settings"
    echo "param: dp or default_proxy - Default Maven settings with enterprise proxy"
    echo "Apache Maven versions available: "
    echo "`find $SISBRIDE_TOOLS -maxdepth 1 -type d -name 'apache-maven*'`"
    exit 1
}

case $1 in
  s | sicoob )
    copy_file $DIR/settings.xml.sicoob $MVN_PATH/conf/settings.xml;
    ;;
  d | default )
    copy_file $DIR/settings.xml.default $MVN_PATH/conf/settings.xml;
    ;;
  dp | default_proxy )
    copy_file $DIR/settings.xml.default.proxy $MVN_PATH/conf/settings.xml;
    ;;
  * )
    show_error
    ;;
esac

echo "export MAVEN_HOME="$SISBRIDE_TOOLS/apache-maven-$2;
echo "export PATH="$SISBRIDE_TOOLS/apache-maven-$2/bin":\$PATH";

