#!/bin/bash

##
# MAIN
##
sudo ls /dev 1> /dev/null 2> /dev/null

echo "---------------------------"
echo "JDK installed versions list"
echo "---------------------------"
echo ""
sudo ls -1 /Library/Java/JavaVirtualMachines;

read -p "Enter JDK version to remove (ex1: jdk1.8.0_201.jdk, ex2: jdk-9.0.4.jdk) or CTRL+C to cancel: " JAVA_VERSION_TO_REMOVE

echo "Removing /Library/Java/JavaVirtualMachines/"$JAVA_VERSION_TO_REMOVE""
sudo rm -rf /Library/Java/JavaVirtualMachines/"$JAVA_VERSION_TO_REMOVE"

echo "Removing /Library/PreferencePanes/JavaControlPanel.prefPane"
sudo rm -rf /Library/PreferencePanes/JavaControlPanel.prefPane

echo "Removing /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin"
sudo rm -rf /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin

echo "Removing /Library/LaunchAgents/com.oracle.java.Java-Updater.plist"
sudo rm -rf /Library/LaunchAgents/com.oracle.java.Java-Updater.plist

echo "Removing /Library/PrivilegedHelperTools/com.oracle.java.JavaUpdateHelper"
sudo rm -rf /Library/PrivilegedHelperTools/com.oracle.java.JavaUpdateHelper

echo "Removing /Library/LaunchDaemons/com.oracle.java.Helper-Tool.plist"
sudo rm -rf /Library/LaunchDaemons/com.oracle.java.Helper-Tool.plist

echo "Removing /Library/Preferences/com.oracle.java.Helper-Tool.plist"
sudo rm -rf /Library/Preferences/com.oracle.java.Helper-Tool.plist
