#!/bin/bash

DIR=`pwd`
if [ $# == 1 ]
then
  DIR=$1;
fi

for a in `ls $DIR`; do {
  DIR_TO_CKECk=$DIR/$a
  if [ -d $DIR_TO_CKECk ] && [ -d $DIR_TO_CKECk/.git ]
  then
    cd $DIR_TO_CKECk;

    echo "--------------------------------------------------------------------------------";
    echo $DIR_TO_CKECk;
    echo "--------------------------------------------------------------------------------";
    git status -s;
    echo "pull";
    git pull;
    git status -s;
    echo;

    cd $DIR;
  fi
}; done;

exit $?
