#!/bin/bash

##
# This script need two other files: environment.proxy and environment.noproxy
##
configure_proxy_environment() {
  sudo cp /home/anderson/homeoffice/bash-scripts/home/proxy/environment.proxy /etc/environment;
}

configure_noproxy_environment() {
  sudo cp /home/anderson/homeoffice/bash-scripts/home/proxy/environment.noproxy /etc/environment;
  unset http_proxy
  unset https_proxy
  unset ftp_proxy
  unset no_proxy
}

configure_proxy_gsettings_pac() {
  gsettings set org.gnome.system.proxy autoconfig-url "http://pac.zscaler.net/sicoob.com.br/sicoob.pac"
  gsettings set org.gnome.system.proxy mode "auto"
}

configure_noproxy_gsettings_pac() {
  gsettings set org.gnome.system.proxy autoconfig-url ""
  gsettings set org.gnome.system.proxy mode "none"
}

configure_proxy_gsettings_http() {
  gsettings set org.gnome.system.proxy ignore-hosts "['localhost', '127.0.0.0/8', '*sicoob.com.br', '*bancoob.com.br', '*bancoob.br', '*homologacao.com.br', 'gis*', 'sicoob*', '10.210.50.252', 'sicoobnet.com.br', 'vsProdBackofficePortal', 'vsprodbackofficeportal', 'clustersflex', '*sisbr.coop.br', '10.221.1.58', '10.220.1.240']"
  gsettings set org.gnome.system.proxy.ftp host "189.8.69.42"
  gsettings set org.gnome.system.proxy.ftp port 80
  gsettings set org.gnome.system.proxy.http host "189.8.69.42"
  gsettings set org.gnome.system.proxy.http port 80
  gsettings set org.gnome.system.proxy.https host "189.8.69.42"
  gsettings set org.gnome.system.proxy.https port 80
  gsettings set org.gnome.system.proxy mode "manual"
}

configure_noproxy_gsettings_http() {
  gsettings set org.gnome.system.proxy ignore-hosts "[]"
  gsettings set org.gnome.system.proxy.ftp host ""
  gsettings set org.gnome.system.proxy.ftp port 0
  gsettings set org.gnome.system.proxy.http host ""
  gsettings set org.gnome.system.proxy.http port 0
  gsettings set org.gnome.system.proxy.https host ""
  gsettings set org.gnome.system.proxy.https port 0
  gsettings set org.gnome.system.proxy mode "none"
}

configure_proxy_routes() {
  sudo route add -net 0.0.0.0 netmask 0.0.0.0 gw 10.238.34.126 dev eth0
}

configure_noproxy_routes() {
  sudo route del -net 0.0.0.0 netmask 0.0.0.0 gw 10.238.34.126 dev eth0
}

configure_proxy_apt() {
  sudo cp /home/anderson/homeoffice/bash-scripts/home/proxy/99proxy /etc/apt/apt.conf.d/
}

configure_noproxy_apt() {
  sudo rm -f /etc/apt/apt.conf.d/99proxy
}

configure_proxy_git() {
  rm -f /home/anderson/.gitconfig;
  cp /home/anderson/homeoffice/bash-scripts/home/proxy/gitconfig /home/anderson/.gitconfig;
}

configure_noproxy_git() {
  rm -f /home/anderson/.gitconfig;
  ln -s /home/anderson/homeoffice/dotfiles/home/gitconfig /home/anderson/.gitconfig;
}

configure_proxy_maven() {
  cp /home/anderson/homeoffice/bash-scripts/home/proxy/settings.xml.nexus /home/anderson/homeoffice/tools/apache-maven-3.2.3/conf/settings.xml;
}

configure_noproxy_maven() {
  cp /home/anderson/homeoffice/bash-scripts/home/proxy/settings.xml.default /home/anderson/homeoffice/tools/apache-maven-3.2.3/conf/settings.xml;
}


##
# show configure
##
show_report() {
  TIME=1;
  
  sudo cat /etc/environment;
  
  sleep $TIME;
  
  gsettings get org.gnome.system.proxy autoconfig-url
  gsettings get org.gnome.system.proxy ignore-hosts
  gsettings get org.gnome.system.proxy.ftp host
  gsettings get org.gnome.system.proxy.ftp port
  gsettings get org.gnome.system.proxy.http host
  gsettings get org.gnome.system.proxy.http port
  gsettings get org.gnome.system.proxy.https host
  gsettings get org.gnome.system.proxy.https port
  gsettings get org.gnome.system.proxy mode
  
  sleep $TIME;

  sudo route;

  sleep $TIME;

  sudo cat /etc/apt/apt.conf.d/99proxy;

  sleep $TIME;

  sudo cat /home/anderson/.gitconfig;

  sleep $TIME;

  sudo cat /home/anderson/homeoffice/tools/apache-maven-3.2.3/conf/settings.xml;

}

##
# show message error
##
show_error() {
  echo "usage: network [p proxy | ps pac | np no_proxy | s show]"
}

##
# main
##
case "$1" in
  p | proxy)
    configure_proxy_environment;
    configure_noproxy_gsettings_pac;
    configure_proxy_gsettings_http;
    configure_proxy_routes;
    configure_proxy_apt;
    configure_proxy_git;
    configure_proxy_maven;
    show_report;
    ;;
  ps | pac)
    configure_noproxy_environment;
    configure_noproxy_gsettings_http;
    configure_proxy_gsettings_pac;
    configure_proxy_routes;
    configure_proxy_apt;
    configure_proxy_git;
    configure_proxy_maven;
    show_report;
    ;;
  np | no_proxy)
    configure_noproxy_environment;
    configure_noproxy_gsettings_http;
    configure_noproxy_gsettings_pac;
    configure_noproxy_routes;
    configure_noproxy_apt;
    configure_noproxy_git;
    configure_noproxy_maven;
    show_report;
    ;;
  s | show)
    show_report;
    ;;
  *)
    show_error;
    exit 1;
esac

exit 0;
