#!/bin/bash

DIR_BASE="/website"
URL="http://svn.sicoob.com.br/fontesbancoob/SISBR/Website/JAVA"

##
#
processar() {
  case $2 in
    "testeintegrado" | "ti")
      AMBIENTE="testeintegrado"
     ;;
     "homologacao" | "homol")
      AMBIENTE="homologacao"
     ;;
     "producao" | "prod")
      AMBIENTE="producao"
     ;;
     "all")
      AMBIENTE="testeintegrado homologacao producao"
     ;;
     *)
      show_usage
     ;;
  esac
  
  case $3 in
    "backoffice" | "bo")
      PERFIL="backoffice"
     ;;
     "processamento" | "proc")
      PERFIL="processamento"
     ;;
     "esb" | "esb")
      PERFIL="esb"
     ;;
     "frontoffice_validacao" | "fov")
      PERFIL="frontoffice_validacao"
     ;;
     "frontoffice_transacional" | "fot")
      PERFIL="frontoffice_transacional"
     ;;
     "all")
      PERFIL="backoffice processamento esb frontoffice_validacao frontoffice_transacional"
     ;;
     *)
      show_usage
     ;;
  esac
  
  case $1 in
    "checkout" | "co")
      COMANDO="svn co"
      for a in $AMBIENTE; do {
        for b in $PERFIL; do {
          rm -rf $DIR_BASE/$a/$b
        } done;
      } done;
     ;;
    "update" | "up")
      COMANDO="svn update"
     ;;
     *)
      show_usage
     ;;
  esac
  
  realizar_operacao_svn "$COMANDO" "$AMBIENTE" "$PERFIL"
}

##
#
realizar_operacao_svn() {
  COMANDO=$1
  AMBIENTE=$2
  PERFIL=$3
  
  for a in $AMBIENTE; do {
    for b in $PERFIL; do {
      $COMANDO $URL/$a/$b/bibliotecas/ $DIR_BASE/$a/$b/bibliotecas
      $COMANDO $URL/$a/$b/comandos/ $DIR_BASE/$a/$b/comandos
      $COMANDO $URL/$a/$b/datasource/ $DIR_BASE/$a/$b/datasource
      $COMANDO $URL/$a/$b/ejb/ $DIR_BASE/$a/$b/ejb
      $COMANDO $URL/$a/$b/mensagens/ $DIR_BASE/$a/$b/mensagens
      $COMANDO $URL/$a/$b/propriedades/ $DIR_BASE/$a/$b/propriedades
      
      if [ $b = "backoffice" ];
      then
        $COMANDO $URL/$a/$b/sisbr.war/WEB-INF/lib $DIR_BASE/$a/$b/sisbr.war/WEB-INF/lib
      fi
    } done;
  } done;
}

##
# 
show_usage() {
  echo "usage: update-website COMANDO AMBIENTE PERFIL"
  echo "comandos: checkout, update"
  echo "ambientes: testeintegrado, homologacao, producao"
  echo "perfis: backoffice, processamento, esb, frontoffice_validacao, frontoffice_transacional"
  exit 1
}

##
# main
if [ $# -eq 3 ] 
then
  processar $1 $2 $3
else 
  show_usage
fi

exit $?
